### ISSUE TITLE
Different message from vscode and terminal

### ISSUE THREAD

**Issue by shafarizkyf** [tightenco/tlint#100]
I have installed tlint globally and tighten-lint for vscode. I setup tlint.json in the project root. But it seems the plugin not reading tlint.json, for example I prefer to disabled the SpaceAfterSoleNotOperator. my code looks something like this

`if(!$this->auth->userid()){
      return redirect('logout');
    }`

in vscode at problems tabs showing "tighten-lint: ! No parenthesis on empty instantiations (NoParensEmptyInstantiations)" but if I run via terminal there is no error which is correct that I ignore that specific rule.

I'm missing something ?

**Comment by loganhenson** [comment]
@shafarizkyf could you open this issue on https://github.com/d9705996/vscode-tighten-lint ?

**Comment by shafarizkyf** [comment]
ah sure, I was searching for that plugin repo but didn't find it.
