### ISSUE TITLE
Error running TLint inspection: this.file.parent must not be null

### ISSUE THREAD

**Issue by tetrode** [tightenco/tlint#103]
Using PHPStorm with TLint plugin

After a while I get this error message:

Error running TLint inspection: this.file.parent must not be null

Restarting PHPStorm solves the issue

**Comment by loganhenson** [comment]
What OS version / PhpStorm version are you running?

**Comment by tetrode** [comment]
*OS*
Linux Mint 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC
2019 x86_64 x86_64 x86_64 GNU/Linux

*PhpStorm* 2019.2.3
Build #PS-192.6817.20, built on September 25, 2019
Licensed to Mark Tetrode
Subscription is active until February 11, 2020
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-29-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: PHPUnit code coverage, com.intellij.ideolog,
com.jetbrains.tlint-plugin, com.atlassian.bitbucket.references,
com.dmarcotte.handlebars, de.espend.idea.laravel, ru.adelf.idea.dotenv

Mark
+ 32 474 92 06 59
.

**Comment by loganhenson** [comment]
Moving this issue to https://github.com/loganhenson/tlint-plugin/issues/8
