### ISSUE TITLE
Discussion: Link to reasons/discussions on tests

### ISSUE THREAD

**Issue by minthemiddle** [tightenco/tlint#106]
- `tlint` is fantastic to follow best practices
- For learning it would be even more useful, if there was a linked *why?* for each test
- These could be links to discussions or articles
- For example I could not easily find an explanation for `NoMethodVisibilityInTestsTest`

**Comment by loganhenson** [comment]
I love this idea!

Some of these are from in person discussions though, and will have to be reconstructed.

I am open to PRs that add reasoning to the lint names in the readme, and will try to extract the discussions where I can from the tighten notes there!

For `NoMethodVisibilityInTestsTest`, I believe the primary point was in a standard PhpUnit suite the test method visibility is redundant (you usually aren't new-ing up PhpUnit class instances).

**Comment by loganhenson** [comment]
We are adding to the readme incrementally as discussion comes up or is revisited 👍

**Comment by abirfo** [comment]
6d3d741aac69bb62af9b93d4991ae1705410b3e1
