### ISSUE TITLE
Bundle required illuminate deps into tlint to avoid dependency clashes with other Laravel tools

### ISSUE THREAD

**Issue by devramguiao** [tightenco/tlint#116]
Here's the error:

Problem 1
    - Conclusion: don't install tightenco/tlint 3.0.4
    - Conclusion: don't install tightenco/tlint 3.0.3
    - Conclusion: don't install tightenco/tlint 3.0.2
    - Conclusion: remove illuminate/container v5.8.31
    - Installation request for tightenco/tlint ^3.0 -> satisfiable by tightenco/tlint[3.0.0, 3.0.2, 3.0.3, 3.0.4].
    - Conclusion: don't install illuminate/container v5.8.31
    - tightenco/tlint 3.0.0 requires illuminate/view ^6.0 -> satisfiable by illuminate/view[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0].
    - illuminate/view v6.0.0 requires illuminate/container ^6.0 -> satisfiable by illuminate/container[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0].
    - illuminate/view v6.0.1 requires illuminate/container ^6.0 -> satisfiable by illuminate/container[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0].
    - illuminate/view v6.0.2 requires illuminate/container ^6.0 -> satisfiable by illuminate/container[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0].
    - illuminate/view v6.0.3 requires illuminate/container ^6.0 -> satisfiable by illuminate/container[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0].
    - illuminate/view v6.0.4 requires illuminate/container ^6.0 -> satisfiable by illuminate/container[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0].
    - illuminate/view v6.1.0 requires illuminate/container ^6.0 -> satisfiable by illuminate/container[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0].
    - illuminate/view v6.2.0 requires illuminate/container ^6.0 -> satisfiable by illuminate/container[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0].
    - illuminate/view v6.3.0 requires illuminate/container ^6.0 -> satisfiable by illuminate/container[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0].
    - illuminate/view v6.4.1 requires illuminate/container ^6.0 -> satisfiable by illuminate/container[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0].
    - illuminate/view v6.5.0 requires illuminate/container ^6.0 -> satisfiable by illuminate/container[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0].
    - Can only install one of: illuminate/container[v6.0.0, v5.8.31].
    - Can only install one of: illuminate/container[v6.0.1, v5.8.31].
    - Can only install one of: illuminate/container[v6.0.2, v5.8.31].
    - Can only install one of: illuminate/container[v6.0.3, v5.8.31].
    - Can only install one of: illuminate/container[v6.0.4, v5.8.31].
    - Can only install one of: illuminate/container[v6.1.0, v5.8.31].
    - Can only install one of: illuminate/container[v6.2.0, v5.8.31].
    - Can only install one of: illuminate/container[v6.3.0, v5.8.31].
    - Can only install one of: illuminate/container[v6.4.1, v5.8.31].
    - Can only install one of: illuminate/container[v6.5.0, v5.8.31].
    - Installation request for illuminate/container (locked at v5.8.31) -> satisfiable by illuminate/container[v5.8.31]

Composer version 1.9.0 2019-08-02 20:55:32
PHP 7.3.8

**Comment by loganhenson** [comment]
Looks like you have some other globally installed package that uses illuminate/container v5.x (Laravel 5.x), and are trying to install the latest version of tlint globally (Which is updated to Laravel 6.x). You can try to install tlint as a project dependency instead (`composer require tightenco/tlint` for a Laravel 6 project instead of `composer global require tightenco/tlint`) OR upgrade your other global packages that may rely on illuminate/container (likely valet or laravel-installer)

**Comment by loganhenson** [comment]
We should be able to bundle the blade compiler into tlint to avoid this common issue (especially with the updated release cadence), looking into this.

**Comment by devramguiao** [comment]
Hi Logan! Is this linter only for Laravel6?

**Comment by loganhenson** [comment]
@devramguiao No, the linter is not only for Laravel 6, I have published a new version that should ease the dependency requirements you were running into (v3.0.5), could you try upgrading?
