### ISSUE TITLE
Does not work with Symfony Console 5

### ISSUE THREAD

**Issue by minthemiddle** [tightenco/tlint#121]
I just a had fresh install with the following latest Laravel tools:
- PHP 7.4
- Laravel Installer 3.0.1
- Composer version 1.9.1
- Laravel Valet 2.7.0

These packages all use Symfony 5's `console`, (`v5.0.1` according to `composer.lock`).
`tlint` does not install with this version:

`tightenco/tlint 3.0.0 requires symfony/console ^4.3 -> satisfiable by symfony/console[v4.3.0, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1].`

Simply changing  `"symfony/console": "^4.3",` to `"symfony/console": "^4.3|^5.0"` might solve the problem, but I could not run your tests (could not get your Docker setup replicated in a reasonable time).

**Comment by loganhenson** [comment]
You should be able to PR against it and have travis run the tests (I suspect your assumption is correct, and that will resolve it). Otherwise I will check it out as soon as possible, thanks for the heads up!

**Comment by minthemiddle** [comment]
Here you go: https://github.com/tightenco/tlint/pull/122

**Comment by loganhenson** [comment]
Awesome, I'll get this in Friday along with https://github.com/tightenco/tlint/pull/120, thanks so much for taking the time to PR / raise the issue! You are certainly on the edge 😄

**Comment by loganhenson** [comment]
Closed by https://github.com/tightenco/tlint/pull/122
