### ISSUE TITLE
PHP notice thrown when using tlint

### ISSUE THREAD

**Issue by dakira** [tightenco/tlint#129]
I get the following notice repeatedly when using tlint:

```
PHP Notice:  Undefined property: PhpParser\Node\Expr\New_::$name in /Users/me/.composer/vendor/tightenco/tlint/src/Linters/RequestValidation.php on line 32
```

It doesn't hinder tlint from working but it doesn't look nice in the build-logs. :)

**Comment by loganhenson** [comment]
I have a PR up to address this, but could you provide a small code sample that triggers this? I'm just curious

**Comment by dakira** [comment]
Sure! I figured out that this snippet in a controller will cause the notice:

```php
public function store()
{
    // stuff
    if ($condition) {
        return back()
            ->with('errors', (new ViewErrorBag)->add('field', 'message'))
            ->withInput(request()->all());
    }
}
```
