### ISSUE TITLE
tlint always returns an error when using `--json`

### ISSUE THREAD

**Issue by d9705996** [tightenco/tlint#135]
Hi,

As part of a review on an [issue](https://github.com/d9705996/vscode-tighten-lint/issues/2) for the VSCode integration I have noticed a change in behaviour of the `--json` flag since [v3.0.9](https://github.com/tightenco/tlint/compare/v3.0.8...v3.0.9).

`src/Commands/LintCommand.php` now always returns `self::LINTS_FOUND_OR_ERROR` regardless of whether there are errors.   In the extension if the return code of the tlint command is not `0` then the output isn't processed as it is assumed the command failed.  

I can change the behaviour of the extension to ignore the error but since the json format is mostly useful for IDE integration I would suggest it be better to return `self::NO_LINTS_FOUND_OR_SUCCESS` and allow the consumer to parse the JSON object that is always returned to identify whether there are any linting errors.

Is there any reason for the change in behaviour that I am missing?  Otherwise happy to add a PR to change the return value.

**Comment by loganhenson** [comment]
There is a test covering that `LINTS_FOUND_OR_ERROR` (1) is returned when there _are lints_, however there is not a test for the opposite case (so this was likely an oversight in the release 😄)

The somewhat confusing nature of these commands is basically in cases where it is used in CI and it is an "pass(0)/fail(1)" check. With this perspective does the current behavior seem reasonable? I believe it _should_ return `NO_LINTS_FOUND_OR_SUCCESS` (0) if there are no lints found, but I don't see a test for that 😅 

Thoughts @d9705996 ?

**Comment by d9705996** [comment]
@loganhenson - there are a couple of ways I can think of tackling this

1. Revert the previous behaviour when using `--json` it always returns 0.  The behaviour without `--json` returns the correct exit code and could be used for ci.  I also think the output of non-json is more readable for CI as json is quite hard to read unless pretty printed (which tlint doesn't afaik) As `--json` is documented as mainly for IDE integration this makes sense and would only be a patch release as the consumer API wont change (from before the regression). Should just need some additional docs

2. Change all linters to follow unix style 0 for no lints and 1 for any lints (or maybe even the count of lints as return code is a common pattern).  This would be a breaking change IMHO  as the consumer API is changing.  I can fix the vscode extension but this might break the other integrations which is an important consideration.

3.  Do option 2 but with a command line flag to like `--raise-errors` defaulting to false to preserve the  behaviour of returning 0 but when enabled would return 0/1 for CI purposes

For me option 1 is the easiest as the extension would need amended ;-) but I am happy to make changes if needed.  If you think option 2 or 3 then I am happy to have a try at adding a PR but might need some help.

**Comment by d9705996** [comment]
On reflection I would disregard option 3 as this would be a breaking change for anyone using tlint in CI without `--json` which is a bad idea as builds that would previously fail with lint errors would start passing.

**Comment by loganhenson** [comment]
At this point I'm fine to make the change that is easiest for you 😄 The phpstorm extension does not look at the code iirc, and so long as we aren't changing the non --json return code it doesn't particularly matter to me 😄

**Comment by d9705996** [comment]
@loganhenson - to confirm change `--json` to always return 0 constant and add test(s)?

If so I'll try and get a PR tomorrow

**Comment by loganhenson** [comment]
@d9705996 yes that sounds good 👍
