### ISSUE TITLE
issue with "Class members of differing visibility must be separated by a blank line"

### ISSUE THREAD

**Issue by PercleChiu** [tightenco/tlint#137]
something like this  generates this error. i'm not sure if it's intentional. The only way i can get rid of the error is to remove that comment block. Are we not allowed to put a comment block above variables?

```
class MyClass
{
    public const MY_CONST = 'value';

    /**
     * this is a comment block
     */
    protected $my_var = 'my-value';
}
```

**Comment by loganhenson** [comment]
This might be a bug, I'll take a look next chance I get 👍

**Comment by plebedz-sc** [comment]
I have the same error. Any news?

**Comment by loganhenson** [comment]
This was a bit of a heavy handed lint that is now disabled in the preset for `^4.0`, thanks for your patience!
