### ISSUE TITLE
Alphabetical Order on Imports is not working properly

### ISSUE THREAD

**Issue by devramguiao** [tightenco/tlint#140]
Here's my code:

`use Illuminate\Foundation\Testing\RefreshDatabase;`

`use Mockery;`

`use Tests\TestCase;`

`use Uptc\Models\RcAccount as Account;`

`use Uptc\Models\ServiceWebSite as Site;`

`use Uptc\Models\ServiceWebTest as Test;`

`use Uptc\Utils\ServiceWebTester as Tester;`

`use Uptc\Models\Ute;`

When I ran "tlint", it gives me this error:

![image](https://user-images.githubusercontent.com/32057766/76629663-9bf20880-6579-11ea-9cc2-ac273920cd5f.png)

Please let me know how can I fix this issue. Thanks!

**Comment by bakerkretzmar** [comment]
@devramguiao that error message refers to _all_ imports—your last two aren't in alphabetical order, they should be swapped so that the `Utils` namespace appears after all the `Models`:

```php
use Uptc\Models\Ute;
use Uptc\Utils\ServiceWebTester as Tester;
```

**Comment by mattstauffer** [comment]
@devramguiao If you updated to the latest version, the message will be a little bit clearer--it won't mention "(the first segment)". Thanks to @sbine for fixing that.

**Comment by devramguiao** [comment]
Thank you for clarifying.
