### ISSUE TITLE
Error in Linting

### ISSUE THREAD

**Issue by devramguiao** [tightenco/tlint#144]
Please see the screenshot below:
![image](https://user-images.githubusercontent.com/32057766/77154350-78c5dc80-6ad6-11ea-9626-ccdae9002235.png)

I am encountering this PHP notice when I tried to lint. I also have a json file with this config:
`{`
`    "preset": "laravel",`
`    "disabled": ["NoInlineVarDocs", "QualifiedNamesOnlyForClassName", "PureRestControllers"],`
`    "excluded": [`
`            "tests/"`
`    ]`
`}`

Is it connected to this config? Please let me know. Thank you!

**Comment by loganhenson** [comment]
Hey @devramguiao thanks for reporting this issue! Do you think you could give me a code example that triggers this? E.g. run the linter on the smallest case you can find that reproduces this error, and share that code? Thanks!

**Comment by loganhenson** [comment]
@devramguiao still having this issue?
