### ISSUE TITLE
Tlint command not found.

### ISSUE THREAD

**Issue by Gazzza20** [tightenco/tlint#146]
Hi,

I am new to laravel, So I apologise for the silly question.

I have installed this package both globally and locally, When I try and run tlint in my terminal I get
**-bash: tlint: command not found**

Would you be able to advise in where I am going wrong.

Thanks,

**Comment by loganhenson** [comment]
Hey @Gazzza20 can you response with the output from running the command `composer global info`?

**Comment by Gazzza20** [comment]
tightenco/tlint           3.0.12  Tighten linter for Laravel conventions

**Comment by loganhenson** [comment]
Is the global composer bin directory in your path?

**Comment by Gazzza20** [comment]
Sorry, Do you mean the path I run in the terminal?
Really am sorry for being a pain.

**Comment by loganhenson** [comment]
https://stackoverflow.com/questions/25373188/how-to-place-the-composer-vendor-bin-directory-in-your-path

**Comment by Gazzza20** [comment]
Ok, I will give that a read.

**Comment by loganhenson** [comment]
Or in video form: https://laracasts.com/series/setup-a-mac-dev-machine-from-scratch/episodes/6

**Comment by Gazzza20** [comment]
Ok, I will give that a read. I can get results if I run ~/.composer/vendor/tightenco/tlint/bin/tlint. The main cause of my issue is I can't seem to get it to run with gitlab CI
