### ISSUE TITLE
plugin phpstorm - not working on windows 10

### ISSUE THREAD

**Issue by stonkeep** [tightenco/tlint#148]
The phpstorm plugin is not  working on Windows 10
but the `tlint ` command works globally

What's going on?

**Comment by loganhenson** [comment]
Hey @stonkeep the phpstorm plugin is not actually maintained by tighten (or in this repository), it is over at https://github.com/loganhenson/tlint-plugin. Unfortunately I don't use windows day to day so debugging windows 10 issues is not something I can easily do, but PRs are welcome on the tlint-plugin repository, thanks!
