### ISSUE TITLE
Incorrect alphabetic order in grouped use statement

### ISSUE THREAD

**Issue by Alexanyasha** [tightenco/tlint#157]
If I use grouped import of classes from same namespace, plugin showing alphabetic ordering error. If there is one group, line with problem must be last. If there is more than one grouped import - no way to satisfy lint. Example of incorrect ordering without solution below.

```
use Admin\Sections\{ PostSection, 
                                   TaskSection, 
                                   UserSection };
use App\Models\{ Post,
                              PostCategory,
                              Task,
                              User };
use App\Observers\PostCategoryObserver;
use App\Policies\{ PostSectionPolicy, 
                              UserSectionPolicy };
use View;
```

**Comment by loganhenson** [comment]
Group use statements isn't something that is on the roadmap for supporting, PRs are welcome though!
