### ISSUE TITLE
Ensure Laravel config preset passes for fresh laravel install

### ISSUE THREAD

**Issue by loganhenson** [tightenco/tlint#94]

**Comment by josecanhelp** [comment]
It looks like we can remove `NoMethodVisibilityInTests` from the Laravel presets. It's been in the default ExampleTest file and the generator for a while now.

**Comment by josecanhelp** [comment]
What do we want to do in the case where the Laravel repo doesn't follow the Laravel preset?

**Comment by loganhenson** [comment]
@josecanhelp I believe the Laravel preset should be modified to pass on the latest stable version of the Laravel Repo
