### ISSUE TITLE
Call to undefined method PhpParser\Node\Expr\Variable::toString()

### ISSUE THREAD

**Issue by opiy-org** [tightenco/tlint#96]
2.1.5 (27d6789b20d3cfde228393469a239d2d2fe9a1ad)
laravel 5.8

`PHP Fatal error:  Uncaught Error: Call to undefined method PhpParser\Node\Expr\Variable::toString() in /var/www/html/vendor/tightenco/tlint/src/Linters/NoUnusedImports.php:34
Stack trace:
#0 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeVisitor/FindingVisitor.php(42): Tighten\Linters\NoUnusedImports->Tighten\Linters\{closure}(Object(PhpParser\Node\Expr\ClassConstFetch))
#1 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): PhpParser\NodeVisitor\FindingVisitor->enterNode(Object(PhpParser\Node\Expr\ClassConstFetch))
#2 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Arg))
#3 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#4 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\MethodCall))
#5 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeT in /var/www/html/vendor/tightenco/tlint/src/Linters/NoUnusedImports.php on line 34`

**Comment by opiy-org** [comment]
any news?

**Comment by loganhenson** [comment]
@opiy-org could you try v2.1.6 for me?

**Comment by opiy-org** [comment]
seems like latest version at packagist is 2.1.5
https://packagist.org/packages/tightenco/tlint

**Comment by loganhenson** [comment]
@opiy-org Sorry, I hadn't updated the composer version, try now (`2.1.7`)? (https://packagist.org/packages/tightenco/tlint#2.1.7)

**Comment by opiy-org** [comment]
2.1.7
not the same, but imho related...

PHP Fatal error:  Uncaught Error: Call to undefined method PhpParser\Node\Expr\PropertyFetch::**toString**() in /var/www/project2/src/vendor/tightenco/tlint/src/Linters/UseAuthHelperOverFacade.php:33
Stack trace:
#0 /var/www/project2/src/vendor/nikic/php-parser/lib/PhpParser/NodeVisitor/FindingVisitor.php(42): Tighten\Linters\UseAuthHelperOverFacade->Tighten\Linters\{closure}(Object(PhpParser\Node\Expr\StaticCall))
#1 /var/www/project2/src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): PhpParser\NodeVisitor\FindingVisitor->enterNode(Object(PhpParser\Node\Expr\StaticCall))
#2 /var/www/project2/src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\MethodCall))
#3 /var/www/project2/src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\MethodCall))
#4 /var/www/project2/src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser in /var/www/project2/src/vendor/tightenco/tlint/src/Linters/UseAuthHelperOverFacade.php on line 33

**Comment by loganhenson** [comment]
@opiy-org Ah you are right, it looks like your code makes use of dynamic static calls which were not tested against previously, could you try another update? (v2.1.8)

**Comment by opiy-org** [comment]
works fine, thnx!
